// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Experience {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    role?: string;
    company?: string;
    dates?: string;
    logo?: { data: Media };
    body?: string;
    date?: Date;
  };
}
export interface Experience_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  role?: string;
  company?: string;
  dates?: string;
  logo?: Media_Plain;
  body?: string;
  date?: Date;
}

export interface Experience_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  role?: string;
  company?: string;
  dates?: string;
  logo?: number;
  body?: string;
  date?: Date;
}

export interface Experience_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  role?: string;
  company?: string;
  dates?: string;
  logo?: AdminPanelRelationPropertyModification<Media_Plain>;
  body?: string;
  date?: Date;
}
