// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Project } from './project';
import { Media_Plain } from '../common/Media';
import { Project_Plain } from './project';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Post {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    body?: any;
    media?: { data: Media[] };
    project?: { data: Project };
    featured: boolean;
  };
}
export interface Post_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  body?: any;
  media?: Media_Plain[];
  project?: Project_Plain;
  featured: boolean;
}

export interface Post_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  body?: any;
  media?: number[];
  project?: number;
  featured: boolean;
}

export interface Post_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  body?: any;
  media?: AdminPanelRelationPropertyModification<Media_Plain>[];
  project?: AdminPanelRelationPropertyModification<Project_Plain>;
  featured: boolean;
}
